
// DUMMY DATA

const awsRegionsWithCountries = [
  { regionCode: "us-east-1", country: "USA (N. Virginia)" },
  { regionCode: "us-east-2", country: "USA (Ohio)" },
  { regionCode: "us-west-1", country: "USA (N. California)" },
  { regionCode: "us-west-2", country: "USA (Oregon)" },
  { regionCode: "ca-central-1", country: "Canada (Central)" },
  { regionCode: "eu-west-1", country: "Ireland" },
  { regionCode: "eu-west-2", country: "UK (London)" },
  { regionCode: "eu-west-3", country: "France (Paris)" },
  { regionCode: "eu-central-1", country: "Germany (Frankfurt)" },
  { regionCode: "eu-central-2", country: "Switzerland (Zurich)" },
  { regionCode: "eu-north-1", country: "Sweden (Stockholm)" },
  { regionCode: "ap-south-1", country: "India (Mumbai)" },
  { regionCode: "ap-south-2", country: "India (Hyderabad)" },
  { regionCode: "ap-northeast-1", country: "Japan (Tokyo)" },
  { regionCode: "ap-northeast-2", country: "South Korea (Seoul)" },
  { regionCode: "ap-northeast-3", country: "Japan (Osaka)" },
  { regionCode: "ap-southeast-1", country: "Singapore" },
  { regionCode: "ap-southeast-2", country: "Australia (Sydney)" },
  { regionCode: "ap-southeast-3", country: "Indonesia (Jakarta)" },
  { regionCode: "ap-southeast-4", country: "Australia (Melbourne)" },
  { regionCode: "sa-east-1", country: "Brazil (São Paulo)" },
  { regionCode: "me-south-1", country: "Bahrain" },
  { regionCode: "me-central-1", country: "UAE (Dubai)" },
  { regionCode: "af-south-1", country: "South Africa (Cape Town)" },
  { regionCode: "il-central-1", country: "Israel (Tel Aviv)" },
  { regionCode: "cn-north-1", country: "China (Beijing)" },
  { regionCode: "cn-northwest-1", country: "China (Ningxia)" },
  { regionCode: "us-gov-west-1", country: "AWS GovCloud (US-West)" },
  { regionCode: "us-gov-east-1", country: "AWS GovCloud (US-East)" }
];


const azureRegions = [
  { code: "australiacentral", countryName: "Australia" },
  { code: "australiacentral2", countryName: "Australia" },
  { code: "australiaeast", countryName: "Australia" },
  { code: "australiasoutheast", countryName: "Australia" },
  { code: "brazilsouth", countryName: "Brazil" },
  { code: "brazilsoutheast", countryName: "Brazil" },
  { code: "canadacentral", countryName: "Canada" },
  { code: "canadaeast", countryName: "Canada" },
  { code: "centralindia", countryName: "India" },
  { code: "centralus", countryName: "USA" },
  { code: "chinanorth", countryName: "China" },
  { code: "chinaeast", countryName: "China" },
  { code: "chinaeast2", countryName: "China" },
  { code: "francecentral", countryName: "France" },
  { code: "francesouth", countryName: "France" },
  { code: "germanynorth", countryName: "Germany" },
  { code: "germanywestcentral", countryName: "Germany" },
  { code: "indiawest", countryName: "India" },
  { code: "indiacentral", countryName: "India" },
  { code: "indiasouth", countryName: "India" },
  { code: "japaneast", countryName: "Japan" },
  { code: "japanwest", countryName: "Japan" },
  { code: "koreacentral", countryName: "South Korea" },
  { code: "koreasouth", countryName: "South Korea " },
  { code: "northcentralus", countryName: "USA" },
  { code: "northeurope", countryName: "Europe" },
  { code: "norwayeast", countryName: "Norway" },
  { code: "norwaywest", countryName: "Norway" },
  { code: "southafricanorth", countryName: "South Africa" },
  { code: "southafricawest", countryName: "South Africa " },
  { code: "southcentralus", countryName: "USA" },
  { code: "southeastasia", countryName: "Singapore" },
  { code: "southindia", countryName: "India" },
  { code: "swedencentral", countryName: "Sweden" },
  { code: "switzerlandnorth", countryName: "Switzerland" },
  { code: "switzerlandwest", countryName: "Switzerland" },
  { code: "uaenorth", countryName: "UAE" },
  { code: "uaecentral", countryName: "UAE" },
  { code: "uksouth", countryName: "UK" },
  { code: "ukwest", countryName: "UK" },
  { code: "westcentralus", countryName: "USA" },
  { code: "westeurope", countryName: "Europe" },
  { code: "westus", countryName: "USA" },
  { code: "westus2", countryName: "USA" },
  { code: "westus3", countryName: "USA" },
];
