const awsRegionsWithCountries = [
  { regionCode: "us-east-1", country: "USA (N. Virginia)" },
  { regionCode: "us-east-2", country: "USA (Ohio)" },
  { regionCode: "us-west-1", country: "USA (N. California)" },
  { regionCode: "us-west-2", country: "USA (Oregon)" },
  { regionCode: "ca-central-1", country: "Canada (Central)" },
  { regionCode: "eu-west-1", country: "Ireland" },
  { regionCode: "eu-west-2", country: "UK (London)" },
  { regionCode: "eu-west-3", country: "France (Paris)" },
  { regionCode: "eu-central-1", country: "Germany (Frankfurt)" },
  { regionCode: "eu-central-2", country: "Switzerland (Zurich)" },
  { regionCode: "eu-north-1", country: "Sweden (Stockholm)" },
  { regionCode: "ap-south-1", country: "India (Mumbai)" },
  { regionCode: "ap-south-2", country: "India (Hyderabad)" },
  { regionCode: "ap-northeast-1", country: "Japan (Tokyo)" },
  { regionCode: "ap-northeast-2", country: "South Korea (Seoul)" },
  { regionCode: "ap-northeast-3", country: "Japan (Osaka)" },
  { regionCode: "ap-southeast-1", country: "Singapore" },
  { regionCode: "ap-southeast-2", country: "Australia (Sydney)" },
  { regionCode: "ap-southeast-3", country: "Indonesia (Jakarta)" },
  { regionCode: "ap-southeast-4", country: "Australia (Melbourne)" },
  { regionCode: "sa-east-1", country: "Brazil (São Paulo)" },
  { regionCode: "me-south-1", country: "Bahrain" },
  { regionCode: "me-central-1", country: "UAE (Dubai)" },
  { regionCode: "af-south-1", country: "South Africa (Cape Town)" },
  { regionCode: "il-central-1", country: "Israel (Tel Aviv)" },
  { regionCode: "cn-north-1", country: "China (Beijing)" },
  { regionCode: "cn-northwest-1", country: "China (Ningxia)" },
  { regionCode: "us-gov-west-1", country: "AWS GovCloud (US-West)" },
  { regionCode: "us-gov-east-1", country: "AWS GovCloud (US-East)" }
];


const azureRegions = [
  { code: "australiacentral", name: "Australia • Canberra" },
  { code: "australiacentral2", name: "Australia • Canberra" },
  { code: "australiaeast", name: "Australia • New South Wales" },
  { code: "australiasoutheast", name: "Australia • Victoria" },
  { code: "brazilsouth", name: "Brazil • São Paulo State" },
  { code: "brazilsoutheast", name: "Brazil • Rio de Janeiro" },
  { code: "canadacentral", name: "Canada • Toronto" },
  { code: "canadaeast", name: "Canada • Québec" },
  { code: "centralindia", name: "India • Pune" },
  { code: "centralus", name: "USA • Iowa" },
  { code: "chinanorth", name: "China • Beijing" },
  { code: "chinaeast", name: "China • Shanghai" },
  { code: "chinaeast2", name: "China • Shanghai" },
  { code: "francecentral", name: "France • Paris" },
  { code: "francesouth", name: "France • Marseille" },
  { code: "germanynorth", name: "Germany • Berlin" },
  { code: "germanywestcentral", name: "Germany • Frankfurt" },
  { code: "indiawest", name: "India • Mumbai" },
  { code: "indiacentral", name: "India • Pune" },
  { code: "indiasouth", name: "India • Chennai" },
  { code: "japaneast", name: "Japan • Tokyo" },
  { code: "japanwest", name: "Japan • Osaka" },
  { code: "koreacentral", name: "South Korea • Seoul" },
  { code: "koreasouth", name: "South Korea • Busan" },
  { code: "northcentralus", name: "USA • Illinois" },
  { code: "northeurope", name: "Europe • Ireland" },
  { code: "norwayeast", name: "Norway • Oslo" },
  { code: "norwaywest", name: "Norway • Stavanger" },
  { code: "southafricanorth", name: "South Africa • Johannesburg" },
  { code: "southafricawest", name: "South Africa • Cape Town" },
  { code: "southcentralus", name: "USA • Texas" },
  { code: "southeastasia", name: "Singapore" },
  { code: "southindia", name: "India • Chennai" },
  { code: "swedencentral", name: "Sweden • Gävle" },
  { code: "switzerlandnorth", name: "Switzerland • Zurich" },
  { code: "switzerlandwest", name: "Switzerland • Geneva" },
  { code: "uaenorth", name: "UAE • Dubai" },
  { code: "uaecentral", name: "UAE • Abu Dhabi" },
  { code: "uksouth", name: "UK • London" },
  { code: "ukwest", name: "UK • Cardiff" },
  { code: "westcentralus", name: "USA • Wyoming" },
  { code: "westeurope", name: "Europe • Netherlands" },
  { code: "westus", name: "USA • California" },
  { code: "westus2", name: "USA • Washington" },
  { code: "westus3", name: "USA • Arizona" },
];
